# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-09-03 14:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sender',
            name='topic',
            field=models.TextField(default='general'),
            preserve_default=False,
        ),
    ]
