# Generated by Django 2.2.4 on 2020-03-26 11:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0002_sender_topic'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sender',
            old_name='messengerSenderID',
            new_name='sender_id',
        ),
    ]
